/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 9:08:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS project_projectid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Project" CASCADE
;

/* Create Tables */

CREATE TABLE "Project"
(
	"Description" text NULL,
	"Name" varchar(100) NULL,
	"Start" varchar NULL,
	"ProjectID" integer NOT NULL   DEFAULT NEXTVAL(('"project_projectid_seq"'::text)::regclass),
	"UserID" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Project" ADD CONSTRAINT "PK_Project"
	PRIMARY KEY ("ProjectID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Project" ADD CONSTRAINT "FK_Project_User"
	FOREIGN KEY ("UserID") REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Project" ADD CONSTRAINT "FK_Project_Project"
	FOREIGN KEY ("ProjectID") REFERENCES "Project" ("ProjectID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE project_projectid_seq INCREMENT 1 START 1
;