/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 14:05:30 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS rating_ratingid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Rating" CASCADE
;

/* Create Tables */

CREATE TABLE "Rating"
(
	"Comment" varchar(100) NULL,
	"Rate" smallint NULL,
	"RatingID" integer NOT NULL   DEFAULT NEXTVAL(('"rating_ratingid_seq"'::text)::regclass),
	"UserID" integer NULL,
	"TaskstepID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Rating" ADD CONSTRAINT "PK_Rating"
	PRIMARY KEY ("RatingID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Rating" ADD CONSTRAINT "FK_Rating_User"
	FOREIGN KEY ("UserID") REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rating" ADD CONSTRAINT "FK_Rating_Taskstep"
	FOREIGN KEY ("TaskstepID") REFERENCES "Taskstep" ("TaskstepID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE rating_ratingid_seq INCREMENT 1 START 1
;