/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 14:06:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS respondent_respondentid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Respondent" CASCADE
;

/* Create Tables */

CREATE TABLE "Respondent"
(
	"Progress" smallint NULL,
	"RespondentID" integer NOT NULL   DEFAULT NEXTVAL(('"respondent_respondentid_seq"'::text)::regclass),
	"UserID" integer NULL,
	"StepID" integer NOT NULL,
	"TaskstepID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Respondent" ADD CONSTRAINT "PK_Respondent"
	PRIMARY KEY ("RespondentID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Respondent" ADD CONSTRAINT "FK_Respondent_User"
	FOREIGN KEY ("UserID") REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Respondent" ADD CONSTRAINT "FK_Respondent_Step"
	FOREIGN KEY ("StepID") REFERENCES "Step" ("StepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Respondent" ADD CONSTRAINT "FK_Respondent_Taskstep"
	FOREIGN KEY ("TaskstepID") REFERENCES "Taskstep" ("TaskstepID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE respondent_respondentid_seq INCREMENT 1 START 1
;