/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 14:04:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS tasktraits_tasktraitsid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Tasktraits" CASCADE
;

/* Create Tables */

CREATE TABLE "Tasktraits"
(
	"TasktraitsID" integer NOT NULL   DEFAULT NEXTVAL(('"tasktraits_tasktraitsid_seq"'::text)::regclass),
	"TaskID" integer NULL,
	"TraitID" integer NULL,
	"Value" varchar(100) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Tasktraits" ADD CONSTRAINT "PK_Tasktraits"
	PRIMARY KEY ("TasktraitsID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Tasktraits" ADD CONSTRAINT "FK_Tasktraits_Task"
	FOREIGN KEY ("TaskID") REFERENCES "Task" ("TaskID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Tasktraits" ADD CONSTRAINT "FK_Tasktraits_Trait"
	FOREIGN KEY ("TraitID") REFERENCES "Trait" ("TraitID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE tasktraits_tasktraitsid_seq INCREMENT 1 START 1
;