/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 13:59:29 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS task_taskid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Task" CASCADE
;

/* Create Tables */

CREATE TABLE "Task"
(
	"Created" varchar NULL,
	"Deadline" varchar NULL,
	"Description" varchar NULL,
	"Name" varchar NULL,
	"Progress" varchar NULL,
	"Rate_max" smallint NULL,
	"Respondents_max" smallint NULL,
	"Startdate" date NULL,
	"Traits" varchar(100) NULL,
	"TaskID" integer NOT NULL   DEFAULT NEXTVAL(('"task_taskid_seq"'::text)::regclass),
	"ProjectID" integer NOT NULL,
	"StepID" integer NULL,
	"UserID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Task" ADD CONSTRAINT "PK_Task"
	PRIMARY KEY ("TaskID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Task" ADD CONSTRAINT "FK_Task_Project"
	FOREIGN KEY ("ProjectID") REFERENCES "Project" ("ProjectID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task" ADD CONSTRAINT "FK_Task_Step"
	FOREIGN KEY ("StepID") REFERENCES "Step" ("StepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Task" ADD CONSTRAINT "FK_Task_User"
	FOREIGN KEY ("UserID") REFERENCES "User" ("UserID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE task_taskid_seq INCREMENT 1 START 1
;