/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 14:03:34 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS trait_traitid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Trait" CASCADE
;

/* Create Tables */

CREATE TABLE "Trait"
(
	"TraitID" integer NOT NULL   DEFAULT NEXTVAL(('"trait_traitid_seq"'::text)::regclass),
	"Name" varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Trait" ADD CONSTRAINT "PK_Trait"
	PRIMARY KEY ("TraitID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Trait" ADD CONSTRAINT "FK_Trait_Traitcategory"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE trait_traitid_seq INCREMENT 1 START 1
;