/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-led-2024 9:05:36 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS user_userid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "User" CASCADE
;

/* Create Tables */

CREATE TABLE "User"
(
	"Birthdate" date NULL,
	"Description" varchar(1000) NULL,
	"Email" varchar NULL,
	"Gender" varchar NULL,
	"Languages" varchar NULL,
	"Login" varchar NULL,
	"Name" varchar NULL,
	"Nickname" varchar NULL,
	"Phone" varchar NULL,
	"Pwd" varchar NULL,
	"Traits" varchar NULL,
	"UserID" integer NOT NULL   DEFAULT NEXTVAL(('"user_userid_seq"'::text)::regclass)
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "User" ADD CONSTRAINT "PK_User"
	PRIMARY KEY ("UserID")
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE user_userid_seq INCREMENT 1 START 1
;